// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProxyMessage.proto

package com.proxy.common.protobuf;

public final class ProxyMessageProtos {
  private ProxyMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProxyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ProxyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 crcCode = 1;</code>
     */
    int getCrcCode();

    /**
     * <code>optional int64 sessionID = 3;</code>
     */
    long getSessionID();

    /**
     * <code>optional bytes type = 4;</code>
     */
    com.google.protobuf.ByteString getType();

    /**
     * <code>optional bytes proxyType = 5;</code>
     */
    com.google.protobuf.ByteString getProxyType();

    /**
     * <code>optional bytes priority = 6;</code>
     */
    com.google.protobuf.ByteString getPriority();

    /**
     * <code>optional bytes command = 8;</code>
     */
    com.google.protobuf.ByteString getCommand();

    /**
     * <code>optional bytes data = 9;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protobuf.ProxyMessage}
   */
  public  static final class ProxyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.ProxyMessage)
      ProxyMessageOrBuilder {
    // Use ProxyMessage.newBuilder() to construct.
    private ProxyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProxyMessage() {
      crcCode_ = 0;
      sessionID_ = 0L;
      type_ = com.google.protobuf.ByteString.EMPTY;
      proxyType_ = com.google.protobuf.ByteString.EMPTY;
      priority_ = com.google.protobuf.ByteString.EMPTY;
      command_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProxyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              crcCode_ = input.readInt32();
              break;
            }
            case 24: {

              sessionID_ = input.readInt64();
              break;
            }
            case 34: {

              type_ = input.readBytes();
              break;
            }
            case 42: {

              proxyType_ = input.readBytes();
              break;
            }
            case 50: {

              priority_ = input.readBytes();
              break;
            }
            case 66: {

              command_ = input.readBytes();
              break;
            }
            case 74: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProxyMessageProtos.internal_static_protobuf_ProxyMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProxyMessageProtos.internal_static_protobuf_ProxyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProxyMessageProtos.ProxyMessage.class, ProxyMessageProtos.ProxyMessage.Builder.class);
    }

    public static final int CRCCODE_FIELD_NUMBER = 1;
    private int crcCode_;
    /**
     * <code>optional int32 crcCode = 1;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>optional int64 sessionID = 3;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString type_;
    /**
     * <code>optional bytes type = 4;</code>
     */
    public com.google.protobuf.ByteString getType() {
      return type_;
    }

    public static final int PROXYTYPE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString proxyType_;
    /**
     * <code>optional bytes proxyType = 5;</code>
     */
    public com.google.protobuf.ByteString getProxyType() {
      return proxyType_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString priority_;
    /**
     * <code>optional bytes priority = 6;</code>
     */
    public com.google.protobuf.ByteString getPriority() {
      return priority_;
    }

    public static final int COMMAND_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString command_;
    /**
     * <code>optional bytes command = 8;</code>
     */
    public com.google.protobuf.ByteString getCommand() {
      return command_;
    }

    public static final int DATA_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 9;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (crcCode_ != 0) {
        output.writeInt32(1, crcCode_);
      }
      if (sessionID_ != 0L) {
        output.writeInt64(3, sessionID_);
      }
      if (!type_.isEmpty()) {
        output.writeBytes(4, type_);
      }
      if (!proxyType_.isEmpty()) {
        output.writeBytes(5, proxyType_);
      }
      if (!priority_.isEmpty()) {
        output.writeBytes(6, priority_);
      }
      if (!command_.isEmpty()) {
        output.writeBytes(8, command_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(9, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (crcCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, crcCode_);
      }
      if (sessionID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionID_);
      }
      if (!type_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, type_);
      }
      if (!proxyType_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, proxyType_);
      }
      if (!priority_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, priority_);
      }
      if (!command_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, command_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProxyMessageProtos.ProxyMessage)) {
        return super.equals(obj);
      }
      ProxyMessageProtos.ProxyMessage other = (ProxyMessageProtos.ProxyMessage) obj;

      boolean result = true;
      result = result && (getCrcCode()
          == other.getCrcCode());
      result = result && (getSessionID()
          == other.getSessionID());
      result = result && getType()
          .equals(other.getType());
      result = result && getProxyType()
          .equals(other.getProxyType());
      result = result && getPriority()
          .equals(other.getPriority());
      result = result && getCommand()
          .equals(other.getCommand());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCrcCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionID());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PROXYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getProxyType().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProxyMessageProtos.ProxyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProxyMessageProtos.ProxyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProxyMessageProtos.ProxyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProxyMessageProtos.ProxyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProxyMessageProtos.ProxyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ProxyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ProxyMessage)
        ProxyMessageProtos.ProxyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProxyMessageProtos.internal_static_protobuf_ProxyMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProxyMessageProtos.internal_static_protobuf_ProxyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProxyMessageProtos.ProxyMessage.class, ProxyMessageProtos.ProxyMessage.Builder.class);
      }

      // Construct using com.proxy.common.protobuf.ProxyMessageProtos.ProxyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        crcCode_ = 0;

        sessionID_ = 0L;

        type_ = com.google.protobuf.ByteString.EMPTY;

        proxyType_ = com.google.protobuf.ByteString.EMPTY;

        priority_ = com.google.protobuf.ByteString.EMPTY;

        command_ = com.google.protobuf.ByteString.EMPTY;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProxyMessageProtos.internal_static_protobuf_ProxyMessage_descriptor;
      }

      public ProxyMessageProtos.ProxyMessage getDefaultInstanceForType() {
        return ProxyMessageProtos.ProxyMessage.getDefaultInstance();
      }

      public ProxyMessageProtos.ProxyMessage build() {
        ProxyMessageProtos.ProxyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProxyMessageProtos.ProxyMessage buildPartial() {
        ProxyMessageProtos.ProxyMessage result = new ProxyMessageProtos.ProxyMessage(this);
        result.crcCode_ = crcCode_;
        result.sessionID_ = sessionID_;
        result.type_ = type_;
        result.proxyType_ = proxyType_;
        result.priority_ = priority_;
        result.command_ = command_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProxyMessageProtos.ProxyMessage) {
          return mergeFrom((ProxyMessageProtos.ProxyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProxyMessageProtos.ProxyMessage other) {
        if (other == ProxyMessageProtos.ProxyMessage.getDefaultInstance()) return this;
        if (other.getCrcCode() != 0) {
          setCrcCode(other.getCrcCode());
        }
        if (other.getSessionID() != 0L) {
          setSessionID(other.getSessionID());
        }
        if (other.getType() != com.google.protobuf.ByteString.EMPTY) {
          setType(other.getType());
        }
        if (other.getProxyType() != com.google.protobuf.ByteString.EMPTY) {
          setProxyType(other.getProxyType());
        }
        if (other.getPriority() != com.google.protobuf.ByteString.EMPTY) {
          setPriority(other.getPriority());
        }
        if (other.getCommand() != com.google.protobuf.ByteString.EMPTY) {
          setCommand(other.getCommand());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProxyMessageProtos.ProxyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProxyMessageProtos.ProxyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int crcCode_ ;
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public Builder setCrcCode(int value) {

        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public Builder clearCrcCode() {

        crcCode_ = 0;
        onChanged();
        return this;
      }

      private long sessionID_ ;
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public Builder setSessionID(long value) {

        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public Builder clearSessionID() {

        sessionID_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString type_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes type = 4;</code>
       */
      public com.google.protobuf.ByteString getType() {
        return type_;
      }
      /**
       * <code>optional bytes type = 4;</code>
       */
      public Builder setType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes type = 4;</code>
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString proxyType_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes proxyType = 5;</code>
       */
      public com.google.protobuf.ByteString getProxyType() {
        return proxyType_;
      }
      /**
       * <code>optional bytes proxyType = 5;</code>
       */
      public Builder setProxyType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        proxyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes proxyType = 5;</code>
       */
      public Builder clearProxyType() {

        proxyType_ = getDefaultInstance().getProxyType();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString priority_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes priority = 6;</code>
       */
      public com.google.protobuf.ByteString getPriority() {
        return priority_;
      }
      /**
       * <code>optional bytes priority = 6;</code>
       */
      public Builder setPriority(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes priority = 6;</code>
       */
      public Builder clearPriority() {

        priority_ = getDefaultInstance().getPriority();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString command_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes command = 8;</code>
       */
      public com.google.protobuf.ByteString getCommand() {
        return command_;
      }
      /**
       * <code>optional bytes command = 8;</code>
       */
      public Builder setCommand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes command = 8;</code>
       */
      public Builder clearCommand() {

        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 9;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public Builder clearData() {

        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.ProxyMessage)
    }

    // @@protoc_insertion_point(class_scope:protobuf.ProxyMessage)
    private static final ProxyMessageProtos.ProxyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProxyMessageProtos.ProxyMessage();
    }

    public static ProxyMessageProtos.ProxyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProxyMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProxyMessage>() {
      public ProxyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProxyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProxyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProxyMessage> getParserForType() {
      return PARSER;
    }

    public ProxyMessageProtos.ProxyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ProxyMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ProxyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ProxyMessage.proto\022\010protobuf\"\204\001\n\014Proxy" +
      "Message\022\017\n\007crcCode\030\001 \001(\005\022\021\n\tsessionID\030\003 " +
      "\001(\003\022\014\n\004type\030\004 \001(\014\022\021\n\tproxyType\030\005 \001(\014\022\020\n\010" +
      "priority\030\006 \001(\014\022\017\n\007command\030\010 \001(\014\022\014\n\004data\030" +
      "\t \001(\014B/\n\031com.proxy.common.protobufB\022Prox" +
      "yMessageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_ProxyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_ProxyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ProxyMessage_descriptor,
        new String[] { "CrcCode", "SessionID", "Type", "ProxyType", "Priority", "Command", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
